### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by richardstartin** [flippingbits/cssl#1]
I have ported this to Java. This may or may not be worthwhile since it's not possible to explicitly vectorise the search for the end key in `searchRange`, but measuring the performance will be interesting nonetheless. 

Do you have some test cases that verify the data structure's correctness? I would like to use these as sanity checks for my port.

**Comment by flippingbits** [comment]
Sorry for the late response. Somehow, I didn't see any notification for this issue.

I can't provide any formal test cases at the moment.
