### ISSUE TITLE
This skiplist can only insert sorted data?

### ISSUE THREAD

**Issue by LinChuangwei** [flippingbits/cssl#4]
This skiplist can only insert sorted data?

**Comment by winash12** [comment]
@LinChuangwei Yes I think so. Otherwise the search algorithm would not work as implemented.

**Comment by flippingbits** [comment]
First, I want to apologise for my late response. I somehow did not see any notification about this issue.

The provided implementation works only when the inserted data are pre-sorted.
However, in the ADMS paper, we show how to extend CSSL such that it can process dynamic updates (and also inserts in any order).
